services:
    postgres-db:
      image: postgres:16
      container_name: linkshrink-postgres
      networks:
        - linkshrink-net
      ports:
        - "5442:${POSTGRES_PORT}"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./postgresql/schemas:/docker-entrypoint-initdb.d
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d urls_db"]
        interval: 5s
        timeout: 5s
        retries: 5
      restart: always

    linkshrink-app:
      build: 
        context: .
      container_name: linkshrink-app
      networks:
        - linkshrink-net
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}

        - USERVER_ENABLE_STACK_USAGE_MONITOR=0      
      ports:
        - "${SERVER_PORT:-8080}:8080"
      
      depends_on:
        postgres-db:
          condition: service_healthy

      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp=unconfined

networks:
  linkshrink-net:
    driver: bridge

volumes:
  postgres_data: